update footer links for both donate site and thunderbird donate
mozilla/donate-wagtail pull request #1332
Opened 2021-03-03 07:20 UTC by mmmavis

Closes #1018 
Closes #1072

2021-03-03 21:17 UTC, KalobTaulien approved these changes

2021-03-04 21:48 UTC, taisdesouzalessa requested changes
For the [donate site](https://donate-wagta-issue-1018-o0kkw6.herokuapp.com/en-US/) please replace "Cookie" by "Cookies".

Tks!

2021-03-04 21:52 UTC, mmmavis commented on donate/templates/pages/base_page_master.html
> +                                <a class="footer-links__link link link--dark-bg" href="https://www.mozilla.org/privacy/websites/#cookies" target="_blank" rel="noopener">{% trans "Cookie" %}</a>
```suggestion
                                <a class="footer-links__link link link--dark-bg" href="https://www.mozilla.org/privacy/websites/#cookies" target="_blank" rel="noopener">{% trans "Cookies" %}</a>
```

2021-03-04 22:02 UTC, mmmavis commented
@taisdesouzalessa thanks for catching it! I've updated the PR!

2021-03-04 22:08 UTC, taisdesouzalessa approved these changes
yay! tks Mavis 💯 all good on the Design side!

2021-03-04 22:38 UTC, merged