commented out references of crypto donations
mozilla/donate-wagtail pull request #1609
Opened 2022-01-07 19:44 UTC by danielfmiranda

Closes #1608 
Related PRs/issues # https://github.com/mozilla/foundation.mozilla.org/issues/8011

2022-01-10 16:22 UTC, TheoChevalier approved these changes
Thanks Daniel!
Turns out we can’t comment out part of the content inside a blocktrans, because the comments gets extracted in the string. Commenting out entire blocktrans works, though.

I’ve just created a new blocktrans without the crypto bit, and commented out the old one: 4115f77104e05f6cbd08f7ac2187f57711ff246c

2022-01-10 22:03 UTC, Pomax requested changes

2022-01-10 22:03 UTC, Pomax commented on donate/templates/pages/core/ways_to_give_page_master.html
> +    <!-- Temporarily commenting out crypto-donation info per request https://github.com/mozilla/donate-wagtail/issues/1608 -->
and then the same here of course

2022-01-10 23:48 UTC, danielfmiranda commented on donate/templates/pages/core/ways_to_give_page_master.html
> +    <!-- Temporarily commenting out crypto-donation info per request https://github.com/mozilla/donate-wagtail/issues/1608 -->
Done!

2022-01-10 23:49 UTC, danielfmiranda commented
Thanks for the feedback @Pomax! I have updated the templates to now use comment blocks instead of HTML comments

2022-01-11 00:09 UTC, Pomax approved these changes
nice, looks good to me!

2022-01-11 02:04 UTC, merged