WIP: updated copy for mozilla donate help page
mozilla/donate-wagtail pull request #1674
Opened 2022-07-05 23:42 UTC by danielfmiranda

Closes #1668

2022-07-06 09:55 UTC, TheoChevalier requested changes
Thanks @danielfmiranda, just need to remove some extra spaces, otherwise looks good!

2022-07-06 17:45 UTC, danielfmiranda commented on donate/templates/pages/core/contributor_support_page_master.html
> +                                For technical support, please visit the <a href="{{ firefox_support_url }}"> Firefox support page </a>. For help with a VPN subscription, please visit the <a href="{{
Thanks for the suggestion @TheoChevalier!

I have updated the repo to remove the spaces and re-requested review 👍

2022-07-06 18:39 UTC, TheoChevalier approved these changes
Thanks!

2022-07-06 22:17 UTC, merged

2022-07-12 19:07 UTC, anilkanji commented
Thanks all - this looks good and our stakeholder is pleased!